### ISSUE TITLE
abort_unless

### ISSUE THREAD

**Issue by PovilasKorop** [krekas/bookshop#3]
https://github.com/krekas/bookshop/blob/020d7e615bfb1bf2e20e700ae58198b1052b875c/app/Http/Controllers/BookController.php#L59

1. Aš tai nemėgstu asmeniškai šitų atvirkščių sąlygų.
Rašyčiau `abort_if(xxx, 403)`

2. Taip pat nereikia `auth()->user()->id`, trumpiau `auth()->id()`

**Comment by krekas** [comment]
Dabar paliksiu taip, ateičiai greičiausiai naudosiu abort_if()
