### ISSUE TITLE
validated override?

### ISSUE THREAD

**Issue by PovilasKorop** [krekas/bookshop#5]
https://github.com/krekas/bookshop/blob/020d7e615bfb1bf2e20e700ae58198b1052b875c/app/Http/Requests/CreateBookRequest.php#L36

Keistokas sprendimas. Jeigu, kaip suprantu, reikėjo tiesiog kad adminui būtų approved = 1, tai reikėjo controlleryje padaryti tą paprasčiau negu čia Laravel internals overridinti.

Pvz:

``` 
$data = $request->validated();
$data['approved'] = auth()->user()->admin;
```

**Comment by krekas** [comment]
1. Trumpesnis controlleris :)
2. Dabar rašyčiau taip
````php
$book = auth()->user()->books()->create($request->validated() + ['active' => true])
